### ISSUE TITLE
[Assignment 1] ListView and Intent Class

### ISSUE THREAD

**Issue by HQHAN** [withleedh/androidCurriculum1#1]
Requirement )
- User should be able to see the list item that consists of more than 3 child views, 
  one for Text and another for Image and the other for Button
- User should be able to click on the button and it should lead the user to the native browser so user can see the home page of web page that user has clicked on
- User should be able to scroll list items up and down
- You should use custom adapter by extending adapter class android framework provides

Purpose )
- Learn about how the ListView recycles the child views using Adapter
- Learn about how to manipulate the implicit intent

Deadline)
FW29

**Comment by HQHAN** [comment]
Closing as you've done this assignment

**Comment by withleedh** [comment]
thanks for your regarding.

I hope your condition will be better tomorrow.

thank you.
